version: "3.9"
services:
    traefik:
        image: traefik:2.4
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "80:80"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    frontend:
        build:
            context: frontend/docker/development/nginx
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    frontend-node:
        build:
            context: frontend/docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            REACT_APP_AUTH_URL: http://api.localhost
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

#secrets:
#    api_db_password:
#        file: ./docker/development/secrets/api_db_password
#    api_mailer_password:
#        file: ./docker/development/secrets/api_mailer_password
#    sentry_dsn:
#        file: ./docker/development/secrets/sentry_dsn
#    jwt_encryption_key:
#        file: ./docker/development/secrets/jwt_encryption_key
#    jwt_public_key:
#        file: ./docker/development/secrets/jwt_public_key
#    jwt_private_key:
#        file: ./docker/development/secrets/jwt_private_key
#    backup_aws_secret_access_key:
#        file: ./docker/development/secrets/backup_aws_secret_access_key

#volumes:
#    api-postgres:
#    backup-storage:

networks:
    traefik-public:
        name: traefik-public
